rsa:
  public-key-location: classpath:keys/public.pem
  private-key-location: classpath:keys/private.pem

server:
  port: 8010
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

spring:
 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e-store
    username: root
    password: H123456s

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true
