spring.application.name=user
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/user
spring.sql.init.mode=always
spring.datasource.username=root
spring.datasource.password=H123456s
server.port=1737
logging.level.org.springframework.security=Trace
spring.jpa.generate-ddl=true
# by passing error- schema.sql errors
#spring.sql.init.continue-on-error=true

spring.thymeleaf.cache=false




