spring.application.name=userservice
server.port=1727

spring.data.mongodb.authentication-database=admin

jwt.secret=a_super_secret_base64_encoded_key_that_is_at_least_32_bytes_long_or_44_characters
jwt.expiration=3600000